#!/usr/bin/env python3
"""
ModelWorkflowExecution - Workflow Execution Entity.

Direct Pydantic representation of workflow_executions database table.
Maps 1:1 with database schema for type-safe database operations.

ONEX v2.0 Compliance:
- Suffix-based naming: ModelWorkflowExecution
- UUID correlation tracking
- FSM state validation
- Comprehensive field validation with Pydantic v2
"""

from datetime import datetime
from typing import Any, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from omninode_bridge.infrastructure.validation.jsonb_validators import (
    validate_jsonb_fields,
)
from omninode_bridge.schemas import WORKFLOW_METADATA_SCHEMA
from omninode_bridge.utils.metadata_validator import validate_metadata


class ModelWorkflowExecution(BaseModel):
    """
    Entity model for workflow_executions table.

    This model represents a workflow execution record in the database.
    It maps directly to the workflow_executions table schema.

    Database Table: workflow_executions
    Primary Key: id (UUID, auto-generated)
    Unique Key: correlation_id
    Indexes: correlation_id, namespace, current_state

    Workflow States (FSM):
    - PENDING: Workflow created, not yet started
    - PROCESSING: Workflow actively executing
    - COMPLETED: Workflow finished successfully
    - FAILED: Workflow encountered an error

    Example:
        >>> from uuid import uuid4
        >>> from datetime import datetime, timezone
        >>> execution = ModelWorkflowExecution(
        ...     id=uuid4(),
        ...     correlation_id=uuid4(),
        ...     workflow_type="metadata_stamping",
        ...     current_state="PROCESSING",
        ...     namespace="production",
        ...     started_at=datetime.now(timezone.utc)
        ... )
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_assignment=True,
        frozen=False,
        extra="forbid",
        populate_by_name=True,
    )

    # Primary key (auto-generated by database)
    id: Optional[UUID] = Field(
        default=None,
        description="Primary key UUID (auto-generated by database)",
    )

    # Unique correlation identifier
    correlation_id: UUID = Field(
        ...,
        description="UUID correlation identifier for the workflow",
    )

    # Workflow classification
    workflow_type: str = Field(
        ...,
        description="Type of workflow being executed",
        min_length=1,
        max_length=100,
    )

    # FSM state
    current_state: str = Field(
        ...,
        description="Current FSM state (PENDING, PROCESSING, COMPLETED, FAILED)",
        min_length=1,
        max_length=50,
    )

    # Multi-tenant isolation
    namespace: str = Field(
        ...,
        description="Namespace for multi-tenant workflow isolation",
        min_length=1,
        max_length=255,
    )

    # Temporal tracking
    started_at: datetime = Field(
        ...,
        description="Timestamp when the workflow started execution",
    )

    completed_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when the workflow completed (success or failure)",
    )

    # Performance metrics
    execution_time_ms: Optional[int] = Field(
        default=None,
        description="Total workflow execution time in milliseconds",
        ge=0,
    )

    # Error tracking
    error_message: Optional[str] = Field(
        default=None,
        description="Error message if workflow failed",
    )

    # Extended metadata
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Extended workflow metadata",
        json_schema_extra={"db_type": "jsonb"},
    )

    # Auto-managed timestamps
    created_at: Optional[datetime] = Field(
        default=None,
        description="Record creation timestamp (auto-managed by database)",
    )

    updated_at: Optional[datetime] = Field(
        default=None,
        description="Record update timestamp (auto-managed by database)",
    )

    @field_validator("metadata")
    @classmethod
    def validate_metadata_field(cls, v: dict[str, Any]) -> dict[str, Any]:
        """Validate metadata against JSON schema."""
        if v:
            validate_metadata(v, WORKFLOW_METADATA_SCHEMA)
        return v

    @model_validator(mode="after")
    def _validate_jsonb_fields(self) -> "ModelWorkflowExecution":
        """Validate that all JSONB fields have proper annotations."""
        return validate_jsonb_fields(self)
