#!/usr/bin/env python3
"""
ModelFSMTransition - FSM Transition Entity.

Direct Pydantic representation of fsm_transitions database table.
Maps 1:1 with database schema for type-safe database operations.

ONEX v2.0 Compliance:
- Suffix-based naming: ModelFSMTransition
- UUID entity association
- State transition tracking
- Comprehensive field validation with Pydantic v2
"""

from datetime import datetime
from typing import Any, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, model_validator

from omninode_bridge.infrastructure.validation.jsonb_validators import (
    validate_jsonb_fields,
)


class ModelFSMTransition(BaseModel):
    """
    Entity model for fsm_transitions table.

    This model represents FSM state transition records in the database.
    It maps directly to the fsm_transitions table schema.

    Database Table: fsm_transitions
    Primary Key: id (UUID, auto-generated)
    Indexes: entity_id+entity_type, entity_type, created_at, from_state+to_state

    Example:
        >>> from uuid import uuid4
        >>> from datetime import datetime
        >>> transition = ModelFSMTransition(
        ...     id=uuid4(),
        ...     entity_id=uuid4(),
        ...     entity_type="workflow_execution",
        ...     from_state="PROCESSING",
        ...     to_state="COMPLETED",
        ...     transition_event="WORKFLOW_COMPLETED"
        ... )
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_assignment=True,
        frozen=False,
        extra="forbid",
        populate_by_name=True,
    )

    # Primary key (auto-generated by database)
    id: Optional[UUID] = Field(
        default=None,
        description="Primary key UUID (auto-generated by database)",
    )

    # Entity reference
    entity_id: UUID = Field(
        ...,
        description="ID of entity undergoing transition",
    )

    entity_type: str = Field(
        ...,
        description="Type of entity (workflow_execution, bridge_state, etc)",
        min_length=1,
        max_length=100,
    )

    # State transition
    from_state: Optional[str] = Field(
        default=None,
        description="Previous state (NULL for initial state)",
        max_length=50,
    )

    to_state: str = Field(
        ...,
        description="New state after transition",
        min_length=1,
        max_length=50,
    )

    # Transition event
    transition_event: str = Field(
        ...,
        description="Event that triggered the transition",
        min_length=1,
        max_length=100,
    )

    # Transition data
    transition_data: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional transition context",
        json_schema_extra={"db_type": "jsonb"},
    )

    # Auto-managed timestamp
    created_at: Optional[datetime] = Field(
        default=None,
        description="Record creation timestamp (auto-managed by database)",
    )

    @model_validator(mode="after")
    def _validate_jsonb_fields(self) -> "ModelFSMTransition":
        """Validate that all JSONB fields have proper annotations."""
        return validate_jsonb_fields(self)
