#!/usr/bin/env python3
"""
ModelMetadataStamp - Metadata Stamp Entity.

Direct Pydantic representation of metadata_stamps database table.
Maps 1:1 with database schema for type-safe database operations.

ONEX v2.0 Compliance:
- Suffix-based naming: ModelMetadataStamp
- UUID workflow association
- BLAKE3 hash validation
- Comprehensive field validation with Pydantic v2
"""

from datetime import datetime
from typing import Any, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, model_validator

from omninode_bridge.infrastructure.validation.jsonb_validators import (
    validate_jsonb_fields,
)


class ModelMetadataStamp(BaseModel):
    """
    Entity model for metadata_stamps table.

    This model represents metadata stamp audit records in the database.
    It maps directly to the metadata_stamps table schema.

    Database Table: metadata_stamps
    Primary Key: id (UUID, auto-generated)
    Foreign Key: workflow_id → workflow_executions(id) (nullable)
    Indexes: workflow_id, file_hash, namespace, created_at

    Example:
        >>> from uuid import uuid4
        >>> from datetime import datetime
        >>> stamp = ModelMetadataStamp(
        ...     id=uuid4(),
        ...     workflow_id=uuid4(),
        ...     file_hash="abc123def456...",
        ...     stamp_data={"stamp_type": "inline"},
        ...     namespace="production"
        ... )
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_assignment=True,
        frozen=False,
        extra="forbid",
        populate_by_name=True,
    )

    # Primary key (auto-generated by database)
    id: Optional[UUID] = Field(
        default=None,
        description="Primary key UUID (auto-generated by database)",
    )

    # Foreign key to workflow_executions (nullable)
    workflow_id: Optional[UUID] = Field(
        default=None,
        description="UUID of workflow that created this stamp (nullable)",
    )

    # File identity
    file_hash: str = Field(
        ...,
        description="BLAKE3 hash of the stamped file (64 hex characters)",
        min_length=64,
        max_length=64,
        pattern=r"^[a-f0-9]{64}$",
    )

    # Stamp data
    stamp_data: dict[str, Any] = Field(
        ...,
        description="Complete stamp data and metadata",
        json_schema_extra={"db_type": "jsonb"},
    )

    # Multi-tenant isolation
    namespace: str = Field(
        ...,
        description="Namespace for multi-tenant stamp isolation",
        min_length=1,
        max_length=255,
    )

    # Auto-managed timestamp
    created_at: Optional[datetime] = Field(
        default=None,
        description="Record creation timestamp (auto-managed by database)",
    )

    @model_validator(mode="after")
    def _validate_jsonb_fields(self) -> "ModelMetadataStamp":
        """Validate that all JSONB fields have proper annotations."""
        return validate_jsonb_fields(self)
