#!/usr/bin/env python3
"""
ModelWorkflowStep - Workflow Step Entity.

Direct Pydantic representation of workflow_steps database table.
Maps 1:1 with database schema for type-safe database operations.

ONEX v2.0 Compliance:
- Suffix-based naming: ModelWorkflowStep
- UUID workflow association
- Step ordering and status tracking
- Comprehensive field validation with Pydantic v2
"""

from datetime import datetime
from typing import Any, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, model_validator

from omninode_bridge.infrastructure.validation.jsonb_validators import (
    validate_jsonb_fields,
)


class ModelWorkflowStep(BaseModel):
    """
    Entity model for workflow_steps table.

    This model represents individual workflow step execution records.
    It maps directly to the workflow_steps table schema.

    Database Table: workflow_steps
    Primary Key: id (UUID, auto-generated)
    Foreign Key: workflow_id → workflow_executions(id)
    Indexes: workflow_id, status, created_at

    Example:
        >>> from uuid import uuid4
        >>> from datetime import datetime
        >>> step = ModelWorkflowStep(
        ...     id=uuid4(),
        ...     workflow_id=uuid4(),
        ...     step_name="hash_generation",
        ...     step_order=1,
        ...     status="completed",
        ...     execution_time_ms=5
        ... )
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_assignment=True,
        frozen=False,
        extra="forbid",
        populate_by_name=True,
    )

    # Primary key (auto-generated by database)
    id: Optional[UUID] = Field(
        default=None,
        description="Primary key UUID (auto-generated by database)",
    )

    # Foreign key to workflow_executions
    workflow_id: UUID = Field(
        ...,
        description="UUID of parent workflow execution",
    )

    # Step identification
    step_name: str = Field(
        ...,
        description="Name of workflow step",
        min_length=1,
        max_length=100,
    )

    step_order: int = Field(
        ...,
        description="Sequential order of step execution",
        ge=0,
    )

    # Step status
    status: str = Field(
        ...,
        description="Step execution status",
        min_length=1,
        max_length=50,
    )

    # Performance metrics
    execution_time_ms: Optional[int] = Field(
        default=None,
        description="Step execution time in milliseconds",
        ge=0,
    )

    # Step data
    step_data: dict[str, Any] = Field(
        default_factory=dict,
        description="Step-specific data and parameters",
        json_schema_extra={"db_type": "jsonb"},
    )

    # Error tracking
    error_message: Optional[str] = Field(
        default=None,
        description="Error message if step failed",
    )

    # Auto-managed timestamp
    created_at: Optional[datetime] = Field(
        default=None,
        description="Record creation timestamp (auto-managed by database)",
    )

    @model_validator(mode="after")
    def _validate_jsonb_fields(self) -> "ModelWorkflowStep":
        """Validate that all JSONB fields have proper annotations."""
        return validate_jsonb_fields(self)
