"""
Pydantic models for ThreadSafeState and agent coordination.

This module provides type-safe data models for state change records,
specialized state containers, and agent coordination metadata.
"""

from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field


class StateChangeRecord(BaseModel):
    """
    Immutable record of a single state change.

    This model tracks all state modifications with full audit trail including
    timestamps, versions, and the agent/step that made the change.

    Attributes:
        timestamp: When the change occurred (UTC)
        version: State version after this change
        key: Key that was changed
        operation: Operation type (set, delete, update, clear)
        old_value: Value before change (None if key didn't exist)
        new_value: Value after change (None for delete operations)
        changed_by: Agent ID or step ID that made the change
    """

    model_config = ConfigDict(frozen=True)  # Immutable for thread safety

    timestamp: datetime = Field(
        description="When the change occurred (UTC)",
        default_factory=lambda: datetime.utcnow(),
    )
    version: int = Field(description="State version after this change", ge=0)
    key: str = Field(description="Key that was changed", min_length=1)
    operation: str = Field(
        description="Operation type: set, delete, update, clear",
        pattern="^(set|delete|update|clear)$",
    )
    old_value: Optional[Any] = Field(default=None, description="Value before change")
    new_value: Optional[Any] = Field(default=None, description="Value after change")
    changed_by: Optional[str] = Field(
        default=None, description="Agent ID or step ID that made the change"
    )


class AgentCoordinationState(BaseModel):
    """
    Typed state container for agent coordination workflows.

    This model provides a structured container for tracking multi-agent
    workflow execution with shared context, completion tracking, and
    phase management.

    Attributes:
        session_id: Unique coordination session identifier
        agent_count: Number of participating agents
        completed_agents: List of agent IDs that have completed
        shared_context: Shared context data accessible to all agents
        generated_files: List of file paths generated by agents
        current_phase: Current workflow phase
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    session_id: str = Field(description="Coordination session ID")
    agent_count: int = Field(description="Number of participating agents", ge=0)
    completed_agents: list[str] = Field(
        default_factory=list, description="IDs of completed agents"
    )
    shared_context: dict[str, Any] = Field(
        default_factory=dict, description="Shared context data"
    )
    generated_files: list[str] = Field(
        default_factory=list, description="List of generated files"
    )
    current_phase: str = Field(
        default="initialization", description="Current workflow phase"
    )


class CodeGenerationState(BaseModel):
    """
    Typed state container for code generation workflows.

    This model provides a structured container for tracking code generation
    progress including contract parsing, model generation, validator generation,
    test generation, and quality metrics.

    Attributes:
        workflow_id: Unique workflow execution identifier
        contracts_parsed: Parsed contract data by contract name
        generated_models: Model name to file path mapping
        generated_validators: Validator name to file path mapping
        generated_tests: Test name to file path mapping
        type_registry: Type name to definition mapping
        import_statements: Shared import statements
        quality_metrics: Quality scores by metric name
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    workflow_id: str = Field(description="Workflow execution ID")
    contracts_parsed: dict[str, Any] = Field(
        default_factory=dict, description="Parsed contracts"
    )
    generated_models: dict[str, str] = Field(
        default_factory=dict, description="Model name → file path"
    )
    generated_validators: dict[str, str] = Field(
        default_factory=dict, description="Validator name → file path"
    )
    generated_tests: dict[str, str] = Field(
        default_factory=dict, description="Test name → file path"
    )
    type_registry: dict[str, str] = Field(
        default_factory=dict, description="Type name → definition"
    )
    import_statements: list[str] = Field(
        default_factory=list, description="Shared imports"
    )
    quality_metrics: dict[str, float] = Field(
        default_factory=dict, description="Quality scores"
    )
