-- =============================================================================
-- SUPERSEDED (OMN-16759): this file no longer creates anything.
-- =============================================================================
-- Ticket: OMN-16759. Originally authored by OMN-15570 (Gateway lift Phase 0,
--         item G3) as the gateway_link_health projection + status view.
--
-- Replacement (the file that actually creates the relation now):
--   docker/migrations/forward/nodes/node_gateway_link_health_write_effect/
--     0001_create_gateway_link_health.sql
--
-- WHAT WENT WRONG
--   This was a FLAT migration. The flat loop connects to exactly one database,
--   `omnibase_infra` (omninode_infra k8s/migrations/omnibase-infra-migrate.yaml,
--   DB_NAME; the identical POSTGRES_DB default in this repo's
--   scripts/run-forward-migrations.sh). But every object it declared was
--   qualified into `omninode_internal`, which is a schema of the APPLICATION
--   database -- physical name `omnidash_analytics`
--   (docker/catalog/database-topology/*.yaml). To make those names resolve in a
--   database that has no such schema, line 77 opened with
--
--       CREATE SCHEMA IF NOT EXISTS omninode_internal;
--
--   CREATE SCHEMA requires CREATE on the DATABASE, which role_omnibase_infra
--   does not hold on the managed instance, and `IF NOT EXISTS` does not rescue
--   it: Postgres checks the privilege BEFORE it checks existence. The migrate
--   Job failed with
--
--       psql:/work/100_create_gateway_link_health.sql:77:
--         ERROR:  permission denied for database omnibase_infra
--
--   exhausted its backoff limit, and -- because it is migration-order 1 of 6 and
--   runs BEFORE the overlay apply and the runtime digest pin -- took EVERY
--   onex-dev staging deploy down with it, not only the one that surfaced it
--   (omninode_infra run 33080116991). Same statement, same class as OMN-16249 on
--   nodes/node_projection_registration/0005_create_projection_watermarks.sql,
--   which stalled deploy run 32301533344 eight days earlier.
--
-- WHY THIS FILE IS A NO-OP RATHER THAN A CORRECTED ONE
--   Read live from the managed instance before this change was written:
--
--     omnibase_infra      omninode_internal schema ................ ABSENT
--                         role_omnibase_infra CREATE on database ... false
--                         schema_migrations row for this file ...... 0 (never applied)
--     omnidash_analytics  omninode_internal schema ................ PRESENT
--                         omninode_internal.gateway_link_health .... ABSENT
--     onex-dev runtime DSN (AWS Secrets Manager onex-dev/omninode-runtime-db):
--                         user omninode_runtime, database omnidash_analytics
--
--   Three roads out, two of them closed:
--     * Assert the schema instead of creating it (the OMN-16249 remedy) --
--       closed: the schema does not exist in omnibase_infra, so the assert
--       trades a permission error for a divide-by-zero on the same lane.
--     * Re-target the objects at `public` -- closed: the application-database
--       SQL gate rejects it ("application relation target
--       'public.gateway_link_health' is prohibited in public"), and its
--       grandfather baseline is frozen and shrink-only.
--     * Deliver the relation through the NODE loop, which connects to
--       omnidash_analytics as its own role -- open, and it is the fix
--       scripts/ci/check_flat_migration_foreign_connect.py itself names for a
--       flat migration whose target is a database the flat runner never reaches.
--
--   The node loop it is. The DDL moved verbatim (minus the CREATE SCHEMA, plus
--   the OMN-16249 assert probe) to the replacement path above, and its ownership
--   already matched that home before the move: omninode_infra
--   k8s/migrations/application-relation-ownership.yaml records
--   gateway_link_health as database_ref `application`, schema
--   `omninode_internal`. The flat file was the drift.
--
-- WHY THE FILE IS NOT DELETED
--   Applied migration history is preserved permanently, never deleted or
--   rewritten out of existence (operator ruling 2026-08-04, OMN-15695; the same
--   rule 098_create_omninode_internal_schema.sql is kept alive under). The
--   compose lanes DID apply this file's original bytes -- there the runner
--   connects as the postgres superuser, so the CREATE SCHEMA succeeded and the
--   relations physically exist as omnibase_infra.omninode_internal.* on those
--   lanes. Their ledger rows stay valid and their runner keeps skipping this
--   file on filename, exactly as before. Nothing about those lanes changes.
--
--   Disposing of that now-orphaned copy on the compose lanes is deliberately NOT
--   done here: dropping a relation a running lane may hold rows in is not a
--   migration's business to decide unattended. It is tracked as OMN-16759
--   residual work, and
--   docker/migrations/rollback/rollback_100_create_gateway_link_health.sql
--   carries the statements for an operator who wants it gone.
--
-- The statement below exists so the runner records a normal applied row for this
-- file on lanes that never ran it (the managed lane), rather than the file being
-- statement-free. It reads no relation and needs no privilege.
-- =============================================================================

SELECT 'node:node_gateway_link_health_write_effect:0001_create_gateway_link_health.sql'
       AS migration_100_superseded_by;
