# PostgreSQL Connection Management Subcontract - Connection Pool Integration Pattern
# This subcontract defines connection pooling and database management patterns for PostgreSQL adapter

contract_type: "postgres_connection_management_subcontract"
contract_version:
  major: 1
  minor: 0
  patch: 0

metadata:
  name: "PostgresConnectionManagementSubcontract"
  description: "Connection pool management and database operations integration pattern"
  author: "ONEX Framework Team"
  created: "2025-09-11"
  purpose: "Define consistent connection management and database operation patterns"

business_logic:
  pattern: "connection_management"
  ai_agent:
    capabilities: ["connection_pooling", "transaction_management", "health_monitoring"]
    coordination_patterns: ["pool_management", "connection_lifecycle"]
    performance_targets:
      connection_acquisition_latency: "<50ms"
      query_execution_latency: "<100ms"
      pool_efficiency: ">90%"

# Connection Management Strategy
connection_strategy:
  name: "PostgresConnectionStrategy"
  description: "Enterprise-grade PostgreSQL connection management with pooling and monitoring"

  # Connection pool configuration
  pool_configuration:
    connection_pool_settings:
      min_connections: 5
      max_connections: 50
      connection_timeout: "10s"
      idle_timeout: "300s"
      max_connection_lifetime: "3600s"

    pool_health_monitoring:
      health_check_interval: "30s"
      connection_validation_query: "SELECT 1"
      failed_connection_threshold: 3
      pool_recovery_strategy: "gradual_replenishment"

  # Transaction management patterns
  transaction_patterns:
    isolation_levels:
      - "read_uncommitted"
      - "read_committed" # default
      - "repeatable_read"
      - "serializable"

    transaction_strategies:
      short_transactions:
        max_duration: "30s"
        retry_attempts: 3
        rollback_on_timeout: true

      long_transactions:
        max_duration: "300s"
        retry_attempts: 1
        rollback_on_timeout: true
        monitoring_enabled: true

      batch_transactions:
        batch_size: 100
        commit_interval: "10s"
        rollback_on_partial_failure: true

# Database Operation Patterns
operation_patterns:
  query_execution:
    read_operations:
      - pattern: "single_row_fetch"
        timeout: "5s"
        caching_enabled: false

      - pattern: "bulk_data_fetch"
        timeout: "30s"
        streaming_enabled: true
        batch_size: 1000

    write_operations:
      - pattern: "single_insert"
        timeout: "10s"
        return_generated_keys: true

      - pattern: "bulk_insert"
        timeout: "60s"
        batch_size: 500
        transaction_required: true

      - pattern: "update_operations"
        timeout: "30s"
        optimistic_locking: true
        affected_rows_validation: true

  # Prepared statement management
  prepared_statements:
    caching_strategy: "lru_cache"
    max_cached_statements: 100
    statement_timeout: "300s"
    auto_prepare_threshold: 5

# Connection Lifecycle Management
lifecycle_management:
  connection_acquisition:
    acquisition_strategy: "fair_queuing"
    max_wait_time: "30s"
    connection_validation: true

  connection_release:
    cleanup_strategy: "automatic"
    resource_validation: true
    connection_reset: true

  connection_monitoring:
    active_connection_tracking: true
    idle_connection_cleanup: true
    connection_leak_detection: true

# Health Check Integration
health_integration:
  database_health:
    connectivity_check:
      query: "SELECT version()"
      timeout: "5s"
      frequency: "60s"

    performance_check:
      slow_query_threshold: "1s"
      connection_pool_utilization_threshold: "80%"
      active_connection_limit: "90%"

  health_status_reporting:
    status_levels:
      - "healthy": "all_checks_passing"
      - "degraded": "some_checks_failing"
      - "unhealthy": "critical_checks_failing"

    health_metrics:
      - "connection_pool_size"
      - "active_connections"
      - "idle_connections"
      - "failed_connection_attempts"
      - "average_query_time"

# Error Handling and Recovery
error_handling:
  connection_errors:
    network_failures:
      retry_strategy: "exponential_backoff"
      max_retries: 3
      backoff_multiplier: 2
      recovery_action: "connection_pool_refresh"

    authentication_failures:
      retry_strategy: "none"
      alert_strategy: "immediate_security_alert"
      recovery_action: "credential_validation"

    resource_exhaustion:
      detection: "connection_pool_monitoring"
      mitigation: "connection_pool_expansion"
      fallback: "graceful_degradation"

  transaction_errors:
    deadlock_handling:
      detection: "database_error_code_analysis"
      retry_strategy: "random_delay_retry"
      max_retries: 3

    constraint_violations:
      handling: "immediate_rollback"
      reporting: "detailed_error_response"
      recovery: "data_validation_enhancement"

# Performance Optimization
performance_optimization:
  query_optimization:
    query_plan_caching: true
    parameter_binding: true
    batch_execution: true

  connection_optimization:
    connection_warm_up: true
    connection_preallocation: true
    connection_affinity: true

  monitoring_optimization:
    metrics_aggregation: true
    performance_baseline_tracking: true
    auto_scaling_triggers: true

# Schema and Migration Management
schema_management:
  schema_validation:
    startup_validation: true
    runtime_validation: false
    migration_tracking: true

  version_compatibility:
    minimum_postgres_version: "12.0"
    feature_detection: true
    backward_compatibility_checks: true

# Security Integration
security_integration:
  connection_security:
    ssl_enforcement: true
    certificate_validation: true
    connection_encryption: "required"

  access_control:
    schema_level_permissions: true
    query_permission_validation: true
    audit_logging: true

# Observability
observability:
  metrics:
    - "postgres.connection_pool_size"
    - "postgres.active_connections"
    - "postgres.connection_acquisition_time"
    - "postgres.query_execution_time"
    - "postgres.transaction_duration"
    - "postgres.connection_errors"

  events:
    - "connection_acquired"
    - "connection_released"
    - "transaction_started"
    - "transaction_committed"
    - "transaction_rolled_back"
    - "connection_pool_exhausted"

# Code Generation
generation_targets:
  python_runtime:
    connection_managers: true
    pool_monitors: true
    transaction_handlers: true
    health_checkers: true

  configuration_templates:
    connection_pool_config: true
    security_settings: true
    monitoring_config: true

# Integration with Main Contract
integration:
  main_contract_field: "connection_management_configuration"
  mapping_strategy: "dependency_injection"
  backward_compatibility: true
