# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
"""Emit the MCP wrapper ORCHESTRATOR contract for a generated COMPUTE node.

OMN-12841 (contract-native Option B). A generated COMPUTE node never surfaces as
an MCP tool because MCP exposure is orchestrator-only in two source-verified
places:

- ``service_mcp_tool_discovery.py:197-212`` -- the projection->tool converter
  rejects any projection whose ``node_type`` does not start with ``orchestrator``.
- ``service_mcp_tool_sync.py`` -- the Kafka registration consumer exposure rule.

Option A (relax the gate for ``node-type:compute``) was rejected: it bends a
transport surface to special-case generation provenance and forks the MCP gate
logic permanently. Option B (this module) keeps the gate orchestrator-only and
emits, ALONGSIDE the generated COMPUTE node, a thin declarative ORCHESTRATOR
wrapper (CONTRACT + ``handler_routing`` only, no custom node logic) whose
contract declares ``mcp.expose=true`` + a ``tool_name`` and routes the inbound
MCP invocation envelope to the generated COMPUTE handler. The wrapper is the
contract-native MCP surface for the COMPUTE capability; it satisfies the existing
gate without modifying it.

This emitter is pure and deterministic (no I/O): given a
``ModelGeneratedComputeNodeSpec`` it returns a ``ModelMCPWrapperEmission``
carrying both the COMPUTE contract (verbatim) and the ORCHESTRATOR wrapper
contract. The node-generation pipeline persists both artifacts.
"""

from __future__ import annotations

import yaml

from omnibase_core.types import JsonType
from omnibase_infra.models.mcp.model_generated_compute_node_spec import (
    ModelGeneratedComputeNodeSpec,
)
from omnibase_infra.models.mcp.model_mcp_wrapper_emission import (
    ModelMCPWrapperEmission,
)
from omnibase_infra.topics import (
    build_generated_tool_invoke_suffix,
    build_generated_tool_result_suffix,
)


class ServiceMCPWrapperContractEmitter:
    """Pure emitter of the MCP wrapper ORCHESTRATOR contract for a COMPUTE node.

    The wrapper contract is contract-native: ``ORCHESTRATOR_GENERIC`` node_type,
    ``mcp.expose=true`` + ``tool_name``, and a single ``payload_type_match``
    handler route to the generated COMPUTE handler. It is the MCP-exposed entity
    that satisfies the unchanged orchestrator-only MCP gate.
    """

    # Naming/topic conventions for the generated wrapper surface.
    _WRAPPER_NAME_SUFFIX = "_orchestrator"
    _WRAPPER_NODE_TYPE = "ORCHESTRATOR_GENERIC"

    def emit(self, spec: ModelGeneratedComputeNodeSpec) -> ModelMCPWrapperEmission:
        """Emit both the COMPUTE contract and the ORCHESTRATOR wrapper contract.

        Args:
            spec: Strongly-typed spec for the generated COMPUTE node.

        Returns:
            A ``ModelMCPWrapperEmission`` carrying the verbatim COMPUTE contract
            and the declarative ORCHESTRATOR wrapper contract YAML.
        """
        wrapper_name = f"{spec.node_name}{self._WRAPPER_NAME_SUFFIX}"
        # Topic suffixes are composed + validated by the canonical topics module
        # (no hardcoded literals here -- preserves the no-hardcoded-topics gate).
        invoke_topic = build_generated_tool_invoke_suffix(spec.tool_name)
        result_topic = build_generated_tool_result_suffix(spec.tool_name)

        # Declarative wrapper contract -- CONTRACT + handler_routing only.
        # The single route forwards the inbound invocation payload to the
        # generated COMPUTE handler; the orchestrator owns no business logic.
        wrapper_contract: dict[str, JsonType] = {
            "name": wrapper_name,
            "node_type": self._WRAPPER_NODE_TYPE,
            "contract_version": {"major": 1, "minor": 0, "patch": 0},
            "node_version": "1.0.0",
            "description": (
                f"Declarative MCP wrapper orchestrator for generated COMPUTE node "
                f"'{spec.node_name}'. Routes the inbound MCP invocation to the "
                f"generated COMPUTE handler. Generated by OMN-12841 (Option B)."
            ),
            "mcp": {
                "expose": True,
                "tool_name": spec.tool_name,
                "description": spec.description,
                "timeout_seconds": 30,
            },
            "event_bus": {
                "version": {"major": 1, "minor": 0, "patch": 0},
                "subscribe_topics": [invoke_topic],
                "publish_topics": [result_topic],
            },
            "input_model": {
                "name": spec.invocation_input_model_name,
                "module": spec.invocation_input_model_module,
                "description": (
                    f"Invocation input for generated COMPUTE node '{spec.node_name}'."
                ),
            },
            "output_model": {
                "name": spec.invocation_output_model_name,
                "module": spec.invocation_output_model_module,
                "description": (
                    f"Invocation output for generated COMPUTE node '{spec.node_name}'."
                ),
            },
            "handler_routing": {
                "routing_strategy": "payload_type_match",
                "handlers": [
                    {
                        "event_model": {
                            "name": spec.invocation_input_model_name,
                            "module": spec.invocation_input_model_module,
                        },
                        "handler": {
                            "name": spec.compute_handler_class,
                            "module": spec.compute_handler_module,
                        },
                        "output_events": [spec.invocation_output_model_name],
                    }
                ],
            },
        }

        wrapper_contract_yaml = yaml.safe_dump(
            wrapper_contract,
            sort_keys=False,
            default_flow_style=False,
        )

        return ModelMCPWrapperEmission(
            compute_node_name=spec.node_name,
            wrapper_node_name=wrapper_name,
            tool_name=spec.tool_name,
            compute_contract_yaml=spec.compute_contract_yaml,
            wrapper_contract_yaml=wrapper_contract_yaml,
        )


__all__ = ["ServiceMCPWrapperContractEmitter"]
