#!/usr/bin/env python3
"""
ModelMetadataStampInput - Metadata Stamp Audit Input.

Input model for persisting metadata stamp audit records in PostgreSQL.
Provides comprehensive audit trail of all metadata stamps created
through the bridge orchestrator.

ONEX v2.0 Compliance:
- Suffix-based naming: ModelMetadataStampInput
- UUID workflow association
- BLAKE3 hash validation
- Comprehensive field validation with Pydantic v2
"""

from datetime import datetime
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class ModelMetadataStampInput(BaseModel):
    """
    Input model for metadata stamp audit database operations.

    This model records metadata stamps created during workflow execution,
    providing an audit trail for compliance, debugging, and analytics.
    Each stamp is associated with a workflow (if applicable) and contains
    the full stamp data for verification.

    Database Table: metadata_stamps
    Primary Key: id (UUID, auto-generated)
    Foreign Key: workflow_id → workflow_executions(id) (nullable)
    Indexes: file_hash, namespace, created_at

    Stamp Types:
    - inline: Stamp embedded directly in content
    - standalone: Separate stamp file
    - signature: Cryptographic signature stamp

    Event Sources:
    - STAMP_CREATED: Published by orchestrator after successful stamping

    Use Cases:
    - Audit trail: Track all stamps created over time
    - Compliance: Provide evidence of stamping operations
    - Analytics: Analyze stamp patterns and usage
    - Debugging: Trace stamp creation during workflow execution

    Example (Inline Stamp):
        >>> from uuid import uuid4
        >>> from datetime import datetime
        >>> stamp_input = ModelMetadataStampInput(
        ...     workflow_id=uuid4(),
        ...     file_hash="abc123def456...",
        ...     stamp_data={
        ...         "stamp_type": "inline",
        ...         "stamp_position": "header",
        ...         "file_size_bytes": 1024,
        ...         "content_type": "image/jpeg",
        ...         "stamp_metadata": {
        ...             "created_by": "orchestrator",
        ...             "stamping_service": "metadata-stamping:v1.0.0"
        ...         }
        ...     },
        ...     namespace="production"
        ... )

    Example (Standalone Stamp - No Workflow):
        >>> standalone_stamp = ModelMetadataStampInput(
        ...     workflow_id=None,  # Direct stamping, no workflow
        ...     file_hash="xyz789abc123...",
        ...     stamp_data={
        ...         "stamp_type": "standalone",
        ...         "stamp_file_path": "/stamps/xyz789.stamp",
        ...         "signature": "...base64...",
        ...         "algorithm": "BLAKE3"
        ...     },
        ...     namespace="development"
        ... )
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_assignment=True,
        frozen=False,
        extra="forbid",
    )

    # === Workflow Association ===
    workflow_id: UUID | None = Field(
        default=None,
        description="""
        UUID of the workflow that created this stamp.

        References workflow_executions(id) via foreign key.
        Null for stamps created outside of workflow context
        (e.g., direct API calls, batch operations).

        Links stamps to their originating workflows for
        end-to-end traceability.
        """,
    )

    # === File Identity ===
    file_hash: str = Field(
        ...,
        description="""
        BLAKE3 hash of the stamped file.

        64-character hexadecimal hash generated by BLAKE3 algorithm.
        Serves as the unique identifier for the file content.

        Format: Lowercase hexadecimal, exactly 64 characters
        Example: "abc123def456789abcdef0123456789abcdef0123456789abcdef0123456789"  # pragma: allowlist secret
        """,
        min_length=64,
        max_length=64,
        pattern=r"^[a-f0-9]{64}$",
    )

    # === Stamp Data ===
    stamp_data: dict[str, Any] = Field(
        ...,
        description="""
        Complete stamp data and metadata.

        Contains all information about the stamp, including:
        - Stamp type and format
        - Stamp content or reference
        - Stamping metadata (service version, timestamp, etc.)
        - File metadata (size, type, etc.)
        - Intelligence data (if OnexTree was used)

        Example (Full Stamp Data):
        {
            "stamp_type": "inline",
            "stamp_position": "header",
            "stamp_content": "...base64...",
            "file_metadata": {
                "file_size_bytes": 1024,
                "content_type": "image/jpeg",
                "file_extension": ".jpg"
            },
            "stamping_metadata": {
                "service": "metadata-stamping",
                "version": "1.0.0",
                "timestamp": "2025-10-07T10:30:00Z",
                "execution_time_ms": 2
            },
            "intelligence_metadata": {
                "onextree_enabled": true,
                "classification": "document",
                "confidence": 0.95
            },
            "onex_compliance": {
                "protocol_version": "1.0",
                "namespace": "production",
                "metadata_version": "0.1"
            }
        }
        """,
    )

    # === Multi-Tenant Isolation ===
    namespace: str = Field(
        ...,
        description="""
        Namespace for multi-tenant stamp isolation.

        All stamps within the same namespace are grouped together
        for analytics and compliance reporting.

        Common namespaces:
        - "production": Production environment stamps
        - "staging": Staging environment stamps
        - "development": Development environment stamps
        - "tenant_123": Tenant-specific stamps
        """,
        min_length=1,
        max_length=255,
    )

    # === Temporal Tracking ===
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="""
        Timestamp when this stamp was created.

        Automatically set to current UTC time.
        Used for audit trail timeline and compliance reporting.
        """,
    )
