"""Agent activity model for ONEX workflow coordination."""

from datetime import datetime
from typing import Optional
from uuid import UUID

from omnibase_core.models.model_base import ModelBase
from pydantic import Field, ConfigDict


class ModelAgentActivity(ModelBase):
    """Model for agent activity information in the ONEX workflow coordinator."""

    model_config = ConfigDict(extra="forbid")

    # Agent identification
    agent_id: str = Field(
        ...,
        min_length=1,
        max_length=100,
        description="Unique identifier for the agent"
    )
    agent_name: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Human-readable name of the agent"
    )
    agent_type: str = Field(
        ...,
        description="Type of agent",
        examples=["coordinator", "specialist", "processor", "validator", "orchestrator"]
    )
    agent_version: str = Field(
        default="1.0.0",
        description="Version of the agent software"
    )
    
    # Activity status
    status: str = Field(
        ...,
        description="Current status of the agent activity",
        examples=["idle", "initializing", "running", "waiting", "completed", "failed", "timeout"]
    )
    current_task: str = Field(
        default="idle",
        description="Description of the current task being performed",
        examples=["processing_request", "validating_data", "coordinating_workflow", "waiting_for_dependency"]
    )
    
    # Timing information
    started_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp when agent activity started"
    )
    last_activity_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp of last activity from this agent"
    )
    completed_at: Optional[datetime] = Field(
        None,
        description="Timestamp when agent activity completed"
    )
    total_runtime_seconds: float = Field(
        default=0.0,
        ge=0.0,
        description="Total runtime of the agent in seconds"
    )
    
    # Progress and performance
    progress_percentage: float = Field(
        default=0.0,
        ge=0.0,
        le=100.0,
        description="Progress percentage of current agent task"
    )
    tasks_completed: int = Field(
        default=0,
        ge=0,
        description="Number of tasks completed by this agent"
    )
    tasks_failed: int = Field(
        default=0,
        ge=0,
        description="Number of tasks that failed for this agent"
    )
    
    # Resource utilization
    memory_usage_mb: Optional[float] = Field(
        None,
        ge=0.0,
        description="Current memory usage in megabytes"
    )
    cpu_usage_percentage: Optional[float] = Field(
        None,
        ge=0.0,
        le=100.0,
        description="Current CPU usage percentage"
    )
    network_bytes_sent: int = Field(
        default=0,
        ge=0,
        description="Total network bytes sent by the agent"
    )
    network_bytes_received: int = Field(
        default=0,
        ge=0,
        description="Total network bytes received by the agent"
    )
    
    # Coordination information
    parent_workflow_id: UUID = Field(
        ...,
        description="ID of the parent workflow this agent is part of"
    )
    assigned_step_ids: list[UUID] = Field(
        default_factory=list,
        description="List of workflow step IDs assigned to this agent"
    )
    dependencies: list[str] = Field(
        default_factory=list,
        description="List of agent IDs this agent depends on"
    )
    blocking_agents: list[str] = Field(
        default_factory=list,
        description="List of agent IDs that are blocked by this agent"
    )
    
    # Error handling and recovery
    error_count: int = Field(
        default=0,
        ge=0,
        description="Number of errors encountered by this agent"
    )
    warning_count: int = Field(
        default=0,
        ge=0,
        description="Number of warnings generated by this agent"
    )
    last_error_message: Optional[str] = Field(
        None,
        max_length=1000,
        description="Last error message from this agent"
    )
    recovery_attempts: int = Field(
        default=0,
        ge=0,
        description="Number of recovery attempts made by this agent"
    )
    
    # Communication and messaging
    messages_sent: int = Field(
        default=0,
        ge=0,
        description="Number of messages sent by this agent"
    )
    messages_received: int = Field(
        default=0,
        ge=0,
        description="Number of messages received by this agent"
    )
    last_heartbeat_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp of last heartbeat from this agent"
    )
    
    # Capabilities and configuration
    capabilities: list[str] = Field(
        default_factory=list,
        description="List of capabilities this agent possesses"
    )
    configuration: dict[str, str] = Field(
        default_factory=dict,
        description="Agent-specific configuration parameters"
    )
    
    # Output and results
    output_artifacts: list[str] = Field(
        default_factory=list,
        description="List of output artifacts produced by this agent"
    )
    metrics: dict[str, float] = Field(
        default_factory=dict,
        description="Agent-specific performance metrics"
    )
    
    # Metadata
    priority: str = Field(
        default="normal",
        description="Execution priority for this agent",
        examples=["low", "normal", "high", "critical"]
    )
    tags: list[str] = Field(
        default_factory=list,
        description="Tags for categorizing and filtering agent activities"
    )