#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
#
# generate-local-env.sh -- Generate a complete, working local secret set for
# `onex up core` (OMN-16187).
#
# Every secret the core stack needs is generated on this machine with openssl.
# Nothing here depends on OmniNode's infrastructure: the Infisical instance in
# the core bundle is a container that runs on your host, so its encryption and
# auth secrets are yours to mint. There is no account to create and no vault to
# reach.
#
# The Infisical *machine identity* (INFISICAL_CLIENT_ID / INFISICAL_CLIENT_SECRET
# / INFISICAL_PROJECT_ID) is deliberately NOT generated here. Those are minted by
# scripts/setup-infisical-identity.sh against the Infisical container that
# `onex up core` starts, so they cannot exist until after the first bring-up.
# They are only required for the `runtime` bundle.
#
# Usage:
#   ./scripts/generate-local-env.sh                 # write ~/.omnibase/.env
#   ./scripts/generate-local-env.sh ./.env          # write a specific path
#   ./scripts/generate-local-env.sh --force         # overwrite an existing file
#   ./scripts/generate-local-env.sh --print         # print to stdout, write nothing

set -euo pipefail

FORCE=0
PRINT_ONLY=0
TARGET=""

while [ $# -gt 0 ]; do
    case "$1" in
        --force) FORCE=1 ;;
        --print) PRINT_ONLY=1 ;;
        -h | --help)
            sed -n '5,25p' "$0"
            exit 0
            ;;
        -*)
            echo "error: unknown option '$1'" >&2
            exit 2
            ;;
        *)
            if [ -n "$TARGET" ]; then
                echo "error: more than one output path given" >&2
                exit 2
            fi
            TARGET="$1"
            ;;
    esac
    shift
done

if [ -z "$TARGET" ]; then
    TARGET="${HOME}/.omnibase/.env"
fi

if ! command -v openssl >/dev/null 2>&1; then
    echo "error: openssl is required to generate secrets but was not found" >&2
    exit 1
fi

# Infisical requires a 32-hex-character (16-byte) encryption key; the auth
# secret is a 32-byte base64 value. The rest are opaque passwords.
POSTGRES_PASSWORD="$(openssl rand -hex 32)"
VALKEY_PASSWORD="$(openssl rand -hex 32)"
INFISICAL_ENCRYPTION_KEY="$(openssl rand -hex 16)"
INFISICAL_AUTH_SECRET="$(openssl rand -base64 32)"

# Infisical reaches Valkey over the compose network, so this is the in-network
# service name and port, not the host-published one.
INFISICAL_REDIS_URL="redis://:${VALKEY_PASSWORD}@valkey:6379"

render() {
    cat <<EOF
# Generated by scripts/generate-local-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Local development secrets for \`onex up core\`. Machine-generated, not shared,
# and safe to regenerate — delete the Docker volumes first if you do, since
# Postgres and Valkey keep the password they were initialised with.

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
VALKEY_PASSWORD=${VALKEY_PASSWORD}
INFISICAL_ENCRYPTION_KEY=${INFISICAL_ENCRYPTION_KEY}
INFISICAL_AUTH_SECRET=${INFISICAL_AUTH_SECRET}
INFISICAL_REDIS_URL=${INFISICAL_REDIS_URL}
EOF
}

if [ "$PRINT_ONLY" -eq 1 ]; then
    render
    exit 0
fi

if [ -e "$TARGET" ] && [ "$FORCE" -ne 1 ]; then
    echo "error: $TARGET already exists; pass --force to overwrite it" >&2
    echo "       (overwriting rotates every secret — existing Postgres and" >&2
    echo "        Valkey volumes will reject the new passwords)" >&2
    exit 1
fi

mkdir -p "$(dirname "$TARGET")"
umask 077
render >"$TARGET"
chmod 600 "$TARGET"

echo "Wrote local development secrets to $TARGET"
echo "Next: onex up core   (or: source scripts/onex-cli.sh && infra-up)"
