#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
"""
sync-topic-registry.py (OMN-4962, relocated OMN-9286)

Generates topic constant definitions for omnidash/shared/topics.ts from
the canonical topic_registry.yaml in omniclaude. Ensures the omnidash
consumer always stays in sync with the producer's topic list.

Usage:
    # Check mode (CI): exit 0 if in sync, exit 1 with diff if diverged
    python omnibase_infra/scripts/sync-topic-registry.py --check

    # Write mode (local dev): regenerate the constants block in topics.ts
    python omnibase_infra/scripts/sync-topic-registry.py --write

    # Dry-run: show what would be written without modifying files
    python omnibase_infra/scripts/sync-topic-registry.py --dry-run

Paths are resolved relative to the omni_home root. By default the script
assumes it lives at ``<omni_home>/omnibase_infra/scripts/`` and derives
omni_home as ``Path(__file__).resolve().parents[2]``. Override via the
``OMNI_HOME`` env var or explicit ``--registry`` / ``--topics-ts`` flags
(required in CI where omnibase_infra is cloned standalone).
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print(
        "ERROR: PyYAML is required. Install with: pip install pyyaml", file=sys.stderr
    )
    sys.exit(2)

# ---------------------------------------------------------------------------
# Path resolution
# ---------------------------------------------------------------------------


def _default_omni_home() -> Path:
    env_value = os.environ.get("OMNI_HOME")
    if env_value:
        return Path(env_value).resolve()
    # Script lives at <omni_home>/omnibase_infra/scripts/<this file>
    return Path(__file__).resolve().parents[2]


OMNI_HOME = _default_omni_home()

REGISTRY_PATH = (
    OMNI_HOME / "omniclaude" / "src" / "omniclaude" / "hooks" / "topic_registry.yaml"
)
TOPICS_TS_PATH = OMNI_HOME / "omnidash" / "shared" / "topics.ts"

# Markers in topics.ts that delimit the generated block
BEGIN_MARKER = "// --- BEGIN GENERATED FROM topic_registry.yaml (OMN-4962) ---"
END_MARKER = "// --- END GENERATED FROM topic_registry.yaml (OMN-4962) ---"


def load_registry(path: Path) -> list[dict[str, str]]:
    """Load and validate the topic registry YAML."""
    if not path.exists():
        print(f"ERROR: Registry not found: {path}", file=sys.stderr)
        sys.exit(2)

    with open(path) as f:
        data = yaml.safe_load(f)

    if not isinstance(data, dict):
        print(
            f"ERROR: Registry root must be a mapping, got {type(data).__name__}: {path}",
            file=sys.stderr,
        )
        sys.exit(2)

    topics_obj = data.get("topics", [])
    if not isinstance(topics_obj, list) or not topics_obj:
        print(f"ERROR: No topics found in {path}", file=sys.stderr)
        sys.exit(2)

    for idx, entry in enumerate(topics_obj):
        if not isinstance(entry, dict):
            print(
                f"ERROR: topics[{idx}] must be a mapping, got {type(entry).__name__}: {path}",
                file=sys.stderr,
            )
            sys.exit(2)
        if "topic" not in entry:
            print(
                f"ERROR: topics[{idx}] missing required 'topic' field: {path}",
                file=sys.stderr,
            )
            sys.exit(2)
        if "event_type" not in entry and "topic_base_constant" not in entry:
            print(
                f"ERROR: topics[{idx}] missing 'event_type' or 'topic_base_constant': {path}",
                file=sys.stderr,
            )
            sys.exit(2)

    topics: list[dict[str, str]] = topics_obj
    return topics


def topic_to_constant_name(entry: dict[str, str]) -> str:
    """Convert a registry entry to a TypeScript constant name.

    Uses topic_base_constant if available (e.g. SESSION_STARTED),
    otherwise derives from event_type (e.g. session.started -> SESSION_STARTED).
    """
    if "topic_base_constant" in entry:
        return f"SUFFIX_OMNICLAUDE_{entry['topic_base_constant']}"

    event_type = entry["event_type"]
    name = event_type.upper().replace(".", "_")
    return f"SUFFIX_OMNICLAUDE_{name}"


def generate_constants_block(topics: list[dict[str, str]]) -> str:
    """Generate the TypeScript constants block from registry entries.

    Output is deterministic: sorted alphabetically by constant name.
    """
    lines: list[str] = []
    lines.append(BEGIN_MARKER)
    lines.append("//")
    lines.append("// Auto-generated by scripts/sync-topic-registry.py from")
    lines.append("// omniclaude/src/omniclaude/hooks/topic_registry.yaml")
    lines.append("// Do not edit this block manually. Run:")
    lines.append("//   python scripts/sync-topic-registry.py --write")
    lines.append("//")

    # Build entries and sort by constant name for determinism
    entries: list[tuple[str, str, str]] = []
    for entry in topics:
        const_name = topic_to_constant_name(entry)
        topic = entry["topic"]
        description = entry.get("description", "")
        entries.append((const_name, topic, description))

    entries.sort(key=lambda e: e[0])

    prev_prefix = ""
    for const_name, topic, description in entries:
        # Group by producer (extract from topic name)
        parts = topic.split(".")
        current_prefix = parts[2] if len(parts) > 2 else ""
        if current_prefix != prev_prefix and prev_prefix:
            lines.append("")
        prev_prefix = current_prefix

        if description:
            # Escape */ and collapse newlines so a malformed description can't
            # break the generated JSDoc block.
            safe_description = description.replace("*/", "*\\/").replace("\n", " ")
            lines.append(f"/** {safe_description} */")
        lines.append(f"export const {const_name} = '{topic}';")

    lines.append(END_MARKER)
    return "\n".join(lines) + "\n"


def read_topics_ts(path: Path) -> str:
    """Read the current topics.ts file."""
    if not path.exists():
        print(f"ERROR: topics.ts not found: {path}", file=sys.stderr)
        sys.exit(2)
    return path.read_text()


def replace_generated_block(content: str, new_block: str) -> str:
    """Replace the generated block in topics.ts, or append if not found."""
    pattern = re.compile(
        re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER) + r"\n?",
        re.DOTALL,
    )

    if pattern.search(content):
        return pattern.sub(new_block, content)

    # No existing block - append before the first SUFFIX_ constant section
    # Look for the omniclaude section header
    insert_marker = "// omniclaude Hook Events"
    if insert_marker in content:
        return content.replace(insert_marker, new_block + "\n" + insert_marker)

    # Fallback: append at end
    return content + "\n" + new_block


def extract_existing_block(content: str) -> str | None:
    """Extract the existing generated block from topics.ts."""
    pattern = re.compile(
        re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER) + r"\n?",
        re.DOTALL,
    )
    match = pattern.search(content)
    return match.group(0) if match else None


def check_mode(topics: list[dict[str, str]], topics_ts_path: Path) -> int:
    """Check if topics.ts is in sync. Returns 0 if in sync, 1 if diverged."""
    content = read_topics_ts(topics_ts_path)
    new_block = generate_constants_block(topics)

    existing_block = extract_existing_block(content)
    if existing_block is None:
        print("DRIFT: No generated block found in topics.ts")
        print(f"  Expected block with {len(topics)} topic constants")
        print("  Run: python scripts/sync-topic-registry.py --write")
        return 1

    if existing_block.rstrip() == new_block.rstrip():
        print(
            f"OK: topics.ts is in sync with topic_registry.yaml ({len(topics)} topics)"
        )
        return 0

    print("DRIFT: topics.ts diverged from topic_registry.yaml")
    print()
    print("--- Expected (from registry) ---")
    print(new_block)
    print("--- Actual (in topics.ts) ---")
    print(existing_block)
    print()
    print("Run: python scripts/sync-topic-registry.py --write")
    return 1


def write_mode(topics: list[dict[str, str]], topics_ts_path: Path) -> int:
    """Regenerate the constants block in topics.ts."""
    content = read_topics_ts(topics_ts_path)
    new_block = generate_constants_block(topics)
    updated = replace_generated_block(content, new_block)

    topics_ts_path.write_text(updated)
    print(f"OK: Wrote {len(topics)} topic constants to {topics_ts_path}")
    return 0


def dry_run_mode(topics: list[dict[str, str]]) -> int:
    """Show what would be written."""
    new_block = generate_constants_block(topics)
    print(new_block)
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Sync topic_registry.yaml to topics.ts"
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--check", action="store_true", help="CI mode: check parity")
    group.add_argument("--write", action="store_true", help="Regenerate topics.ts")
    group.add_argument("--dry-run", action="store_true", help="Show generated output")

    parser.add_argument(
        "--registry",
        type=Path,
        default=REGISTRY_PATH,
        help=f"Path to topic_registry.yaml (default: {REGISTRY_PATH})",
    )
    parser.add_argument(
        "--topics-ts",
        type=Path,
        default=TOPICS_TS_PATH,
        help=f"Path to topics.ts (default: {TOPICS_TS_PATH})",
    )

    args = parser.parse_args()

    # Allow overrides via CLI args
    registry_path = args.registry
    topics_ts_path = args.topics_ts

    topics = load_registry(registry_path)

    if args.check:
        return check_mode(topics, topics_ts_path)
    elif args.write:
        return write_mode(topics, topics_ts_path)
    else:
        return dry_run_mode(topics)


if __name__ == "__main__":
    sys.exit(main())
