"""
Test Templates - Jinja2 templates for test file generation.

Generated by NodeTestGeneratorEffect.
ONEX v2.0 Compliance: Provides comprehensive test generation templates.

This module provides Jinja2 templates for generating pytest-compatible test files
for ONEX nodes. Templates support unit, integration, contract, and performance tests.

Template Registry:
- test_unit.py.j2: Unit tests with mocked dependencies
- test_integration.py.j2: Integration tests with real dependencies
- test_contract.py.j2: Contract compliance validation tests
- test_performance.py.j2: Performance benchmarking and load tests
- conftest.py.j2: Shared pytest fixtures and configuration

Usage:
    from jinja2 import Environment, FileSystemLoader
    from pathlib import Path

    # Load template environment
    template_dir = Path(__file__).parent
    env = Environment(loader=FileSystemLoader(template_dir))

    # Render template
    template = env.get_template("test_unit.py.j2")
    rendered = template.render(
        node_name="NodeExampleEffect",
        module_path="omninode_bridge.nodes.example.v1_0_0.node",
        node_type="effect",
        test_contract=test_contract_model,
        fixtures=fixtures_list,
        performance_thresholds=thresholds_dict,
    )

Template Variables:
    Common variables for all templates:
    - node_name: Node class name (e.g., "NodePostgresCrudEffect")
    - module_path: Import path (e.g., "omninode_bridge.nodes.postgres_crud_effect")
    - node_type: "effect", "compute", "reducer", "orchestrator"
    - test_contract: ModelContractTest object
    - contract_file: Path to contract YAML file (for contract tests)

    Test-specific variables:
    - fixtures: List of fixture specifications for conftest.py
    - performance_thresholds: Dict of performance thresholds for performance tests

    Each template is designed to work with the ModelContractTest model which
    provides comprehensive test configuration including:
    - Coverage targets
    - Mock requirements
    - Test configuration (pytest markers, timeouts, etc.)
    - Test targets (methods to test with scenarios)

Version: 1.0.0
"""

from enum import Enum
from pathlib import Path


class EnumTestTemplate(str, Enum):
    """Available test templates."""

    UNIT = "test_unit.py.j2"
    INTEGRATION = "test_integration.py.j2"
    CONTRACT = "test_contract.py.j2"
    PERFORMANCE = "test_performance.py.j2"
    CONFTEST = "conftest.py.j2"


# Template directory
TEMPLATE_DIR = Path(__file__).parent


def get_template_path(template_type: EnumTestTemplate) -> Path:
    """
    Get absolute path to template file.

    Args:
        template_type: Template type enum

    Returns:
        Absolute path to template file

    Raises:
        FileNotFoundError: If template file doesn't exist
    """
    template_path = TEMPLATE_DIR / template_type.value

    if not template_path.exists():
        raise FileNotFoundError(f"Template not found: {template_path}")

    return template_path


def list_available_templates() -> list[str]:
    """
    List all available test templates.

    Returns:
        List of template filenames
    """
    return [template.value for template in EnumTestTemplate]


def get_template_metadata() -> dict[str, dict[str, str | bool]]:
    """
    Get metadata for all templates.

    Returns:
        Dict mapping template names to their metadata
    """
    return {
        "test_unit.py.j2": {
            "description": "Unit tests with mocked dependencies",
            "test_type": "unit",
            "requires_mocks": True,
            "supports_async": True,
            "supports_parametrize": True,
        },
        "test_integration.py.j2": {
            "description": "Integration tests with real dependencies",
            "test_type": "integration",
            "requires_mocks": False,
            "supports_async": True,
            "supports_concurrent": True,
        },
        "test_contract.py.j2": {
            "description": "Contract compliance validation tests",
            "test_type": "contract",
            "requires_mocks": False,
            "validates_onex": True,
            "validates_signatures": True,
        },
        "test_performance.py.j2": {
            "description": "Performance benchmarking and load tests",
            "test_type": "performance",
            "requires_mocks": False,
            "supports_async": True,
            "measures_latency": True,
            "measures_throughput": True,
        },
        "conftest.py.j2": {
            "description": "Shared pytest fixtures and configuration",
            "test_type": "configuration",
            "provides_fixtures": True,
            "configures_pytest": True,
        },
    }


__all__ = [
    "EnumTestTemplate",
    "TEMPLATE_DIR",
    "get_template_path",
    "list_available_templates",
    "get_template_metadata",
]
