"""ONEX Infrastructure Topic Constants.

This module provides platform-reserved topic suffix constants for ONEX infrastructure
components. Domain services should NOT import from this module - domain topics should
be defined in domain contracts.

IMPORTANT: ONEX topics are realm-agnostic. Environment prefixes (dev., prod., etc.)
must NOT appear on the wire. Environment isolation is enforced via envelope identity
and consumer group naming, not topic prefixing. The canonical resolution path is
TopicResolver, which validates suffixes and returns them unchanged.

Exports:
    Platform topic suffix constants (e.g., SUFFIX_NODE_REGISTRATION)
    ALL_PLATFORM_SUFFIXES: Complete tuple of all platform-reserved suffixes
    TopicResolver: Canonical resolver for topic suffix -> concrete Kafka topic
    TopicResolutionError: Error raised when topic resolution fails
"""

from omnibase_infra.topics.model_topic_spec import ModelTopicSpec
from omnibase_infra.topics.platform_topic_suffixes import (
    ALL_INTELLIGENCE_TOPIC_SPECS,
    ALL_OMNIMEMORY_TOPIC_SPECS,
    ALL_PLATFORM_SUFFIXES,
    ALL_PLATFORM_TOPIC_SPECS,
    ALL_PROVISIONED_SUFFIXES,
    ALL_PROVISIONED_TOPIC_SPECS,
    SUFFIX_CONTRACT_DEREGISTERED,
    SUFFIX_CONTRACT_REGISTERED,
    SUFFIX_FSM_STATE_TRANSITIONS,
    SUFFIX_INTELLIGENCE_CLAUDE_HOOK_EVENT,
    SUFFIX_INTELLIGENCE_INTENT_CLASSIFIED,
    SUFFIX_INTELLIGENCE_LLM_CALL_COMPLETED,
    SUFFIX_INTELLIGENCE_PATTERN_DISCOVERED,
    SUFFIX_INTELLIGENCE_PATTERN_LEARNED,
    SUFFIX_INTELLIGENCE_PATTERN_LIFECYCLE_TRANSITION,
    SUFFIX_INTELLIGENCE_PATTERN_LIFECYCLE_TRANSITIONED,
    SUFFIX_INTELLIGENCE_PATTERN_PROMOTED,
    SUFFIX_INTELLIGENCE_PATTERN_STORED,
    SUFFIX_INTELLIGENCE_SESSION_OUTCOME,
    SUFFIX_NODE_HEARTBEAT,
    SUFFIX_NODE_INTROSPECTION,
    SUFFIX_NODE_REGISTRATION,
    SUFFIX_NODE_REGISTRATION_ACKED,
    SUFFIX_OMNIMEMORY_CRAWL_REQUESTED,
    SUFFIX_OMNIMEMORY_CRAWL_TICK,
    SUFFIX_OMNIMEMORY_DOCUMENT_CHANGED,
    SUFFIX_OMNIMEMORY_DOCUMENT_DISCOVERED,
    SUFFIX_OMNIMEMORY_DOCUMENT_INDEXED,
    SUFFIX_OMNIMEMORY_DOCUMENT_REMOVED,
    SUFFIX_REGISTRATION_SNAPSHOTS,
    SUFFIX_REGISTRY_REQUEST_INTROSPECTION,
    SUFFIX_REQUEST_INTROSPECTION,
    SUFFIX_RUNTIME_TICK,
    SUFFIX_TOPIC_CATALOG_CHANGED,
    SUFFIX_TOPIC_CATALOG_QUERY,
    SUFFIX_TOPIC_CATALOG_RESPONSE,
)
from omnibase_infra.topics.topic_resolver import TopicResolutionError, TopicResolver

__all__: list[str] = [
    # Platform suffix constants
    "SUFFIX_NODE_REGISTRATION",
    "SUFFIX_NODE_INTROSPECTION",
    "SUFFIX_NODE_HEARTBEAT",
    "SUFFIX_REQUEST_INTROSPECTION",
    "SUFFIX_FSM_STATE_TRANSITIONS",
    "SUFFIX_RUNTIME_TICK",
    "SUFFIX_REGISTRATION_SNAPSHOTS",
    "SUFFIX_REGISTRY_REQUEST_INTROSPECTION",
    "SUFFIX_CONTRACT_REGISTERED",
    "SUFFIX_CONTRACT_DEREGISTERED",
    "SUFFIX_NODE_REGISTRATION_ACKED",
    # Topic catalog suffix constants
    "SUFFIX_TOPIC_CATALOG_QUERY",
    "SUFFIX_TOPIC_CATALOG_RESPONSE",
    "SUFFIX_TOPIC_CATALOG_CHANGED",
    # Intelligence domain suffix constants
    "SUFFIX_INTELLIGENCE_CLAUDE_HOOK_EVENT",
    "SUFFIX_INTELLIGENCE_SESSION_OUTCOME",
    "SUFFIX_INTELLIGENCE_PATTERN_LIFECYCLE_TRANSITION",
    "SUFFIX_INTELLIGENCE_INTENT_CLASSIFIED",
    "SUFFIX_INTELLIGENCE_LLM_CALL_COMPLETED",
    "SUFFIX_INTELLIGENCE_PATTERN_LEARNED",
    "SUFFIX_INTELLIGENCE_PATTERN_STORED",
    "SUFFIX_INTELLIGENCE_PATTERN_PROMOTED",
    "SUFFIX_INTELLIGENCE_PATTERN_LIFECYCLE_TRANSITIONED",
    "SUFFIX_INTELLIGENCE_PATTERN_DISCOVERED",
    # OmniMemory domain suffix constants
    "SUFFIX_OMNIMEMORY_DOCUMENT_DISCOVERED",
    "SUFFIX_OMNIMEMORY_DOCUMENT_CHANGED",
    "SUFFIX_OMNIMEMORY_DOCUMENT_REMOVED",
    "SUFFIX_OMNIMEMORY_DOCUMENT_INDEXED",
    "SUFFIX_OMNIMEMORY_CRAWL_TICK",
    "SUFFIX_OMNIMEMORY_CRAWL_REQUESTED",
    # Aggregate collections
    "ALL_PLATFORM_SUFFIXES",
    "ALL_PLATFORM_TOPIC_SPECS",
    "ALL_INTELLIGENCE_TOPIC_SPECS",
    "ALL_OMNIMEMORY_TOPIC_SPECS",
    "ALL_PROVISIONED_SUFFIXES",
    "ALL_PROVISIONED_TOPIC_SPECS",
    # Topic spec model
    "ModelTopicSpec",
    # Topic resolution
    "TopicResolver",
    "TopicResolutionError",
]
