#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
# health-tick.sh — Probe .201 infra + LLM endpoints. Fail-loud on down, silent if green.
#
# Schedule: every hour at :03
# Output:   /data/onex/ticks/health-YYYYMMDD-HHmm.md
# Mirror:   rsync to $OMNI_HOME/.onex_state/ticks/ on local Mac (if ONEX_MAC_HOST set)
#
# Services probed:
#   Infrastructure: postgres:5436, redpanda:19092, valkey:16379
#   LLM endpoints:  .201:8000, .201:8001, .200:8100, .200:8101, .200:8102

set -euo pipefail

# Load env
# shellcheck source=/dev/null
source "${HOME}/.omnibase/.env"

OMNI_HOME="${OMNI_HOME:-/home/jonah/Code/omni_home}"
TICK_DIR="/data/onex/ticks"
FRICTION_DIR="${OMNI_HOME}/.onex_state/friction"
TIMEOUT="${TIMEOUT:-5}"
TIMESTAMP="$(date -u +%Y%m%d-%H%M)"
REPORT="${TICK_DIR}/health-${TIMESTAMP}.md"
ONEX_MAC_HOST="${ONEX_MAC_HOST:-}"  # e.g. "jonah@192.168.86.200" — set in .env to enable rsync

mkdir -p "${TICK_DIR}" "${FRICTION_DIR}"

FAIL=0
WARN=0
declare -a RESULTS=()

_probe_tcp() {
    local label="$1" host="$2" port="$3" required="${4:-true}"
    if nc -z -w "${TIMEOUT}" "${host}" "${port}" 2>/dev/null; then
        RESULTS+=("OK   ${label} — ${host}:${port}")
    elif [[ "${required}" == "true" ]]; then
        RESULTS+=("FAIL ${label} — ${host}:${port} (unreachable)")
        FAIL=$((FAIL + 1))
    else
        RESULTS+=("WARN ${label} — ${host}:${port} (unreachable, optional)")
        WARN=$((WARN + 1))
    fi
}

_probe_http() {
    local label="$1" url="$2" required="${3:-true}"
    local status
    status=$(curl -sf --max-time "${TIMEOUT}" -o /dev/null -w "%{http_code}" "${url}/health" 2>/dev/null || true)
    if [[ "${status}" =~ ^2 ]]; then
        RESULTS+=("OK   ${label} — ${url} (HTTP ${status})")
        return
    fi
    # fallback: /v1/models
    status=$(curl -sf --max-time "${TIMEOUT}" -o /dev/null -w "%{http_code}" "${url}/v1/models" 2>/dev/null || true)
    if [[ "${status}" =~ ^2 ]]; then
        RESULTS+=("OK   ${label} — ${url} (/v1/models HTTP ${status})")
        return
    fi
    if [[ "${required}" == "true" ]]; then
        RESULTS+=("FAIL ${label} — ${url} (unreachable)")
        FAIL=$((FAIL + 1))
    else
        RESULTS+=("WARN ${label} — ${url} (unreachable, optional)")
        WARN=$((WARN + 1))
    fi
}

# Infrastructure (required)
_probe_tcp "postgres"  "192.168.86.201" "5436"
_probe_tcp "redpanda"  "192.168.86.201" "19092"
_probe_tcp "valkey"    "192.168.86.201" "16379"

# LLM endpoints (.201 GPU — required)
_probe_http "Qwen3-Coder-30B (RTX5090)"    "http://192.168.86.201:8000"
_probe_http "DeepSeek-R1-14B (RTX4090)"    "http://192.168.86.201:8001"

# LLM endpoints (.200 MLX — optional, may be restarting)
_probe_http "Qwen3-Embedding-8B (M2)"      "http://192.168.86.200:8100" "false"
_probe_http "DeepSeek-R1-32B (M2)"         "http://192.168.86.200:8101" "false"
_probe_http "Qwen3-Next-80B (M2)"          "http://192.168.86.200:8102" "false"

# Determine overall status
if [[ "${FAIL}" -gt 0 ]]; then
    OVERALL="RED"
elif [[ "${WARN}" -gt 0 ]]; then
    OVERALL="YELLOW"
else
    OVERALL="GREEN"
fi

# Write report
{
    echo "# Health Tick — ${TIMESTAMP}"
    echo ""
    echo "**Status**: ${OVERALL}  |  Failures: ${FAIL}  |  Warnings: ${WARN}"
    echo ""
    echo "## Results"
    echo ""
    for r in "${RESULTS[@]}"; do
        echo "- ${r}"
    done
    echo ""
    echo "_Generated by health-tick.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")_"
} > "${REPORT}"

# Write friction entry on failure
if [[ "${FAIL}" -gt 0 ]]; then
    FRICTION_FILE="${FRICTION_DIR}/health-tick-fail-${TIMESTAMP}.md"
    {
        echo "# Friction: health-tick FAIL — ${TIMESTAMP}"
        echo ""
        echo "**Source**: health-tick.sh"
        echo "**Severity**: RED"
        echo ""
        echo "## Failed checks"
        echo ""
        for r in "${RESULTS[@]}"; do
            if [[ "${r}" == FAIL* ]]; then
                echo "- ${r}"
            fi
        done
        echo ""
        echo "_Written at $(date -u +"%Y-%m-%dT%H:%M:%SZ")_"
    } > "${FRICTION_FILE}"
    echo "HEALTH-TICK FAIL: ${FAIL} service(s) down. Report: ${REPORT}" >&2
fi

# Mirror to local Mac (idempotent, best-effort — do not fail tick if rsync fails)
if [[ -n "${ONEX_MAC_HOST}" ]]; then
    rsync -a --quiet "${TICK_DIR}/" "${ONEX_MAC_HOST}:${OMNI_HOME}/.onex_state/ticks/" 2>/dev/null || true
fi

exit "${FAIL}"
