#!/usr/bin/env python3
"""
ModelWorkflowExecution - Workflow Execution Entity.

Strongly-typed Pydantic model representing workflow_executions table.
Includes all database fields including auto-generated columns.

ONEX v2.0 Compliance:
- Suffix-based naming: ModelWorkflowExecution (entity, not input)
- UUID correlation tracking
- FSM state validation
- Complete database schema representation
"""

from datetime import datetime
from typing import Any, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from omninode_bridge.infrastructure.validation.jsonb_validators import (
    validate_jsonb_fields,
)
from omninode_bridge.schemas import WORKFLOW_METADATA_SCHEMA
from omninode_bridge.utils.metadata_validator import validate_metadata


class ModelWorkflowExecution(BaseModel):
    """
    Workflow execution entity (maps to workflow_executions table).

    This entity represents a complete workflow execution record including
    all database-managed fields. Used for type-safe INSERT, UPDATE, and
    QUERY operations through the database adapter.

    Database Table: workflow_executions
    Primary Key: id (auto-generated)
    Unique Constraint: correlation_id
    Indexes: correlation_id, namespace, current_state

    Example (for INSERT):
        >>> from uuid import uuid4
        >>> workflow = ModelWorkflowExecution(
        ...     correlation_id=uuid4(),
        ...     workflow_type="metadata_stamping",
        ...     current_state="PROCESSING",
        ...     namespace="production",
        ...     started_at=datetime.now(timezone.utc)
        ... )

    Example (from database query):
        >>> # Query result includes auto-generated fields
        >>> workflow = ModelWorkflowExecution(
        ...     id=42,
        ...     correlation_id=uuid4(),
        ...     workflow_type="metadata_stamping",
        ...     current_state="COMPLETED",
        ...     namespace="production",
        ...     started_at=datetime.now(timezone.utc),
        ...     completed_at=datetime.now(timezone.utc),
        ...     execution_time_ms=1234,
        ...     created_at=datetime.now(timezone.utc),
        ...     updated_at=datetime.now(timezone.utc)
        ... )
    """

    model_config = ConfigDict(
        str_strip_whitespace=True,
        validate_assignment=True,
        frozen=False,
        extra="forbid",
        populate_by_name=True,  # Allow population from database row
        json_schema_extra={
            "example": {
                "id": 42,
                "correlation_id": "550e8400-e29b-41d4-a716-446655440000",
                "workflow_type": "metadata_stamping",
                "current_state": "COMPLETED",
                "namespace": "production",
                "started_at": "2025-10-08T12:00:00Z",
                "completed_at": "2025-10-08T12:05:23Z",
                "execution_time_ms": 323000,
                "error_message": None,
                "metadata": {"source": "api", "user_id": "user_123"},
                "created_at": "2025-10-08T12:00:00Z",
                "updated_at": "2025-10-08T12:05:23Z",
            }
        },
    )

    # === Database-Generated Fields ===
    id: Optional[int] = Field(
        default=None,
        description="""
        Auto-generated primary key.

        Generated by PostgreSQL sequence on INSERT.
        None when creating new records, populated when reading from database.
        """,
        ge=1,
    )

    # === Workflow Identity ===
    correlation_id: UUID = Field(
        ...,
        description="""
        UUID correlation identifier for the workflow.

        Unique identifier preserved across the entire workflow lifecycle.
        Used for distributed tracing and end-to-end observability.
        """,
    )

    # === Workflow Classification ===
    workflow_type: str = Field(
        ...,
        description="""
        Type of workflow being executed.

        Common values:
        - "metadata_stamping": Standard stamping workflow
        - "batch_stamping": Batch processing workflow
        - "validation": Stamp validation workflow
        - "intelligence_enrichment": OnexTree intelligence workflow
        """,
        min_length=1,
        max_length=100,
    )

    # === FSM State ===
    current_state: str = Field(
        ...,
        description="""
        Current FSM state of the workflow.

        Valid states: PENDING, PROCESSING, COMPLETED, FAILED

        State transitions:
        - PENDING → PROCESSING: Workflow starts
        - PROCESSING → COMPLETED: Workflow succeeds
        - PROCESSING → FAILED: Workflow encounters error
        """,
        min_length=1,
        max_length=50,
    )

    # === Multi-Tenant Isolation ===
    namespace: str = Field(
        ...,
        description="""
        Namespace for multi-tenant workflow isolation.

        All workflows within the same namespace are grouped together
        for aggregation and analytics purposes.
        """,
        min_length=1,
        max_length=255,
    )

    # === Temporal Tracking ===
    started_at: Optional[datetime] = Field(
        default=None,
        description="""
        Timestamp when the workflow started execution.

        Set when WORKFLOW_STARTED event is processed.
        Null for workflows that haven't started yet (PENDING state).
        """,
    )

    completed_at: Optional[datetime] = Field(
        default=None,
        description="""
        Timestamp when the workflow completed (success or failure).

        Set when WORKFLOW_COMPLETED or WORKFLOW_FAILED event is processed.
        Null for workflows still in progress.
        """,
    )

    # === Performance Metrics ===
    execution_time_ms: Optional[int] = Field(
        default=None,
        description="""
        Total workflow execution time in milliseconds.

        Calculated as: (completed_at - started_at) in milliseconds
        Only available after workflow completion.
        """,
        ge=0,
    )

    # === Error Tracking ===
    error_message: Optional[str] = Field(
        default=None,
        description="""
        Error message if workflow failed.

        Only populated when current_state = "FAILED"
        Contains exception message and stack trace details.
        """,
        max_length=2000,
    )

    # === Extended Metadata ===
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="""
        Extended workflow metadata (JSONB column).

        Example:
        {
            "source": "api",
            "user_id": "user_123",
            "api_version": "v1",
            "client_ip": "192.168.1.100",
            "stamping_service_version": "1.0.0",
            "onextree_enabled": true,
            "batch_size": 10
        }
        """,
        json_schema_extra={"db_type": "jsonb"},
    )

    # === Database Timestamps (Auto-Managed) ===
    created_at: Optional[datetime] = Field(
        default=None,
        description="""
        Timestamp when this record was created.

        Auto-managed by PostgreSQL (DEFAULT NOW()).
        Populated when reading from database, None when inserting.
        """,
    )

    updated_at: Optional[datetime] = Field(
        default=None,
        description="""
        Timestamp when this record was last updated.

        Auto-managed by PostgreSQL trigger.
        Updated automatically on every UPDATE operation.
        """,
    )

    @field_validator("metadata")
    @classmethod
    def validate_metadata_field(cls, v: dict[str, Any]) -> dict[str, Any]:
        """Validate metadata against JSON schema."""
        if v:
            validate_metadata(v, WORKFLOW_METADATA_SCHEMA)
        return v

    @model_validator(mode="after")
    def _validate_jsonb_fields(self) -> "ModelWorkflowExecution":
        """Validate that all JSONB fields have proper annotations."""
        return validate_jsonb_fields(self)
