#!/usr/bin/env python3
"""
Sample database effect node with health monitoring and metrics

Generated by OmniNode Code Generator
DO NOT EDIT MANUALLY - Regenerate from contract
"""

import logging
from collections.abc import Awaitable, Callable

from omnibase_core.enums.enum_node_health_status import EnumNodeHealthStatus
from omnibase_core.mixins.mixin_health_check import MixinHealthCheck
from omnibase_core.mixins.mixin_metrics import MixinMetrics
from omnibase_core.models.core.model_container import ModelContainer
from omnibase_core.models.core.model_health_status import ModelHealthStatus
from omnibase_core.nodes.node_effect import NodeEffect

logger = logging.getLogger(__name__)


class NodeSampleDatabaseEffect(NodeEffect, MixinHealthCheck, MixinMetrics):
    """
    Sample database effect node with health monitoring and metrics

    ONEX v2.0 Compliant Effect Node

    Capabilities:
      Built-in Features (NodeEffect):
        - Circuit breakers with failure threshold
        - Retry policies with exponential backoff
        - Transaction support with rollback
        - Concurrent execution control
        - Performance metrics tracking

      Enhanced Features (Mixins):
        - MixinHealthCheck: Health check implementation with async support
        - MixinMetrics: Performance metrics collection
    """

    def __init__(self, container: ModelContainer):
        """Initialize node with container and mixins."""
        # Initialize base classes (Node + Mixins)
        super().__init__(container)

        # Initialize logger
        self.logger = logging.getLogger(self.__class__.__name__)

        # Configure MixinHealthCheck
        self.healthcheck_config = {
            "check_interval_ms": 30000,
            "timeout_seconds": 5.0,
        }

    async def initialize(self) -> None:
        """Initialize node resources and mixins."""
        # Initialize base NodeEffect
        await super().initialize()

        self.logger.info(f"Initializing {self.__class__.__name__}")

        # Setup health checks
        health_checks = self.get_health_checks()
        for check_name, check_func in health_checks:
            self.register_health_check(check_name, check_func)

        self.logger.info(f"{self.__class__.__name__} initialized successfully")

    async def shutdown(self) -> None:
        """Shutdown node and cleanup resources."""
        self.logger.info(f"Shutting down {self.__class__.__name__}")

        # Shutdown base NodeEffect
        await super().shutdown()

    def get_health_checks(
        self,
    ) -> list[
        tuple[
            str,
            Callable[[], Awaitable[ModelHealthStatus]]
            | Callable[[], ModelHealthStatus],
        ]
    ]:
        """
        Register health checks for this node.

        Returns:
            List of (check_name, check_function) tuples where check_function
            is either an async or sync callable returning ModelHealthStatus
        """
        return [
            ("self", self._check_self_health),
            # TODO: Add additional health checks as needed
        ]

    async def _check_self_health(self) -> ModelHealthStatus:
        """
        Check node's own health status.

        Returns:
            Health status model
        """
        try:
            # TODO: Implement actual health check logic
            # Example: Check database connection, API availability, etc.

            return ModelHealthStatus(
                status=EnumNodeHealthStatus.HEALTHY,
                message="Node is healthy",
            )
        except Exception as e:
            self.logger.error(f"Health check failed: {e}")
            return ModelHealthStatus(
                status=EnumNodeHealthStatus.UNHEALTHY,
                message=f"Health check failed: {e!s}",
            )
